package com.finance.shared

public data class CountryMetadata(
    val code: String,
    val displayName: String,
    val defaultCurrency: Currency?
)

public val Country.metadata: CountryMetadata get() = CountryMetadataRegistry.get(this)

internal object CountryMetadataRegistry {
    private val registry: Map<Country, CountryMetadata> = mapOf(
        Country.AD to CountryMetadata("AD", "Andorra", Currency.EUR),
        Country.AE to CountryMetadata("AE", "United Arab Emirates", Currency.AED),
        Country.AF to CountryMetadata("AF", "Afghanistan", Currency.AFN),
        Country.AG to CountryMetadata("AG", "Antigua and Barbuda", Currency.XCD),
        Country.AL to CountryMetadata("AL", "Albania", Currency.ALL),
        Country.AM to CountryMetadata("AM", "Armenia", Currency.AMD),
        Country.AO to CountryMetadata("AO", "Angola", Currency.AOA),
        Country.AR to CountryMetadata("AR", "Argentina", Currency.ARS),
        Country.AT to CountryMetadata("AT", "Austria", Currency.EUR),
        Country.AU to CountryMetadata("AU", "Australia", Currency.AUD),
        Country.AZ to CountryMetadata("AZ", "Azerbaijan", Currency.AZN),
        Country.BA to CountryMetadata("BA", "Bosnia and Herzegovina", Currency.BAM),
        Country.BB to CountryMetadata("BB", "Barbados", Currency.BBD),
        Country.BD to CountryMetadata("BD", "Bangladesh", Currency.BDT),
        Country.BE to CountryMetadata("BE", "Belgium", Currency.EUR),
        Country.BF to CountryMetadata("BF", "Burkina Faso", Currency.XOF),
        Country.BG to CountryMetadata("BG", "Bulgaria", Currency.BGN),
        Country.BH to CountryMetadata("BH", "Bahrain", Currency.BHD),
        Country.BI to CountryMetadata("BI", "Burundi", Currency.BIF),
        Country.BJ to CountryMetadata("BJ", "Benin", Currency.XOF),
        Country.BN to CountryMetadata("BN", "Brunei", Currency.BND),
        Country.BO to CountryMetadata("BO", "Bolivia", Currency.BOB),
        Country.BR to CountryMetadata("BR", "Brazil", Currency.BRL),
        Country.BS to CountryMetadata("BS", "Bahamas", Currency.BSD),
        Country.BT to CountryMetadata("BT", "Bhutan", Currency.BTN),
        Country.BW to CountryMetadata("BW", "Botswana", Currency.BWP),
        Country.BY to CountryMetadata("BY", "Belarus", Currency.BYN),
        Country.BZ to CountryMetadata("BZ", "Belize", Currency.BZD),
        Country.CA to CountryMetadata("CA", "Canada", Currency.CAD),
        Country.CD to CountryMetadata("CD", "DR Congo", Currency.CDF),
        Country.CF to CountryMetadata("CF", "Central African Republic", Currency.XAF),
        Country.CG to CountryMetadata("CG", "Republic of the Congo", Currency.XAF),
        Country.CH to CountryMetadata("CH", "Switzerland", Currency.CHF),
        Country.CI to CountryMetadata("CI", "Ivory Coast", Currency.XOF),
        Country.CL to CountryMetadata("CL", "Chile", Currency.CLP),
        Country.CM to CountryMetadata("CM", "Cameroon", Currency.XAF),
        Country.CN to CountryMetadata("CN", "China", Currency.CNY),
        Country.CO to CountryMetadata("CO", "Colombia", Currency.COP),
        Country.CR to CountryMetadata("CR", "Costa Rica", Currency.CRC),
        Country.CU to CountryMetadata("CU", "Cuba", Currency.CUP),
        Country.CV to CountryMetadata("CV", "Cape Verde", Currency.CVE),
        Country.CY to CountryMetadata("CY", "Cyprus", Currency.EUR),
        Country.CZ to CountryMetadata("CZ", "Czech Republic", Currency.CZK),
        Country.DE to CountryMetadata("DE", "Germany", Currency.EUR),
        Country.DJ to CountryMetadata("DJ", "Djibouti", Currency.DJF),
        Country.DK to CountryMetadata("DK", "Denmark", Currency.DKK),
        Country.DM to CountryMetadata("DM", "Dominica", Currency.XCD),
        Country.DO to CountryMetadata("DO", "Dominican Republic", Currency.DOP),
        Country.DZ to CountryMetadata("DZ", "Algeria", Currency.DZD),
        Country.EC to CountryMetadata("EC", "Ecuador", Currency.USD),
        Country.EE to CountryMetadata("EE", "Estonia", Currency.EUR),
        Country.EG to CountryMetadata("EG", "Egypt", Currency.EGP),
        Country.ER to CountryMetadata("ER", "Eritrea", Currency.ERN),
        Country.ES to CountryMetadata("ES", "Spain", Currency.EUR),
        Country.ET to CountryMetadata("ET", "Ethiopia", Currency.ETB),
        Country.FI to CountryMetadata("FI", "Finland", Currency.EUR),
        Country.FJ to CountryMetadata("FJ", "Fiji", Currency.FJD),
        Country.FR to CountryMetadata("FR", "France", Currency.EUR),
        Country.GA to CountryMetadata("GA", "Gabon", Currency.XAF),
        Country.GB to CountryMetadata("GB", "United Kingdom", Currency.GBP),
        Country.GD to CountryMetadata("GD", "Grenada", Currency.XCD),
        Country.GE to CountryMetadata("GE", "Georgia", Currency.GEL),
        Country.GH to CountryMetadata("GH", "Ghana", Currency.GHS),
        Country.GM to CountryMetadata("GM", "Gambia", Currency.GMD),
        Country.GN to CountryMetadata("GN", "Guinea", Currency.GNF),
        Country.GQ to CountryMetadata("GQ", "Equatorial Guinea", Currency.XAF),
        Country.GR to CountryMetadata("GR", "Greece", Currency.EUR),
        Country.GT to CountryMetadata("GT", "Guatemala", Currency.GTQ),
        Country.GW to CountryMetadata("GW", "Guinea-Bissau", Currency.XOF),
        Country.GY to CountryMetadata("GY", "Guyana", Currency.GYD),
        Country.HK to CountryMetadata("HK", "Hong Kong", Currency.HKD),
        Country.HN to CountryMetadata("HN", "Honduras", Currency.HNL),
        Country.HR to CountryMetadata("HR", "Croatia", Currency.EUR),
        Country.HT to CountryMetadata("HT", "Haiti", Currency.HTG),
        Country.HU to CountryMetadata("HU", "Hungary", Currency.HUF),
        Country.ID to CountryMetadata("ID", "Indonesia", Currency.IDR),
        Country.IE to CountryMetadata("IE", "Ireland", Currency.EUR),
        Country.IL to CountryMetadata("IL", "Israel", Currency.ILS),
        Country.IN to CountryMetadata("IN", "India", Currency.INR),
        Country.IQ to CountryMetadata("IQ", "Iraq", Currency.IQD),
        Country.IR to CountryMetadata("IR", "Iran", Currency.IRR),
        Country.IS to CountryMetadata("IS", "Iceland", Currency.ISK),
        Country.IT to CountryMetadata("IT", "Italy", Currency.EUR),
        Country.JM to CountryMetadata("JM", "Jamaica", Currency.JMD),
        Country.JO to CountryMetadata("JO", "Jordan", Currency.JOD),
        Country.JP to CountryMetadata("JP", "Japan", Currency.JPY),
        Country.KE to CountryMetadata("KE", "Kenya", Currency.KES),
        Country.KG to CountryMetadata("KG", "Kyrgyzstan", Currency.KGS),
        Country.KH to CountryMetadata("KH", "Cambodia", Currency.KHR),
        Country.KI to CountryMetadata("KI", "Kiribati", Currency.AUD),
        Country.KM to CountryMetadata("KM", "Comoros", Currency.KMF),
        Country.KN to CountryMetadata("KN", "Saint Kitts and Nevis", Currency.XCD),
        Country.KP to CountryMetadata("KP", "North Korea", Currency.KPW),
        Country.KR to CountryMetadata("KR", "South Korea", Currency.KRW),
        Country.KW to CountryMetadata("KW", "Kuwait", Currency.KWD),
        Country.KZ to CountryMetadata("KZ", "Kazakhstan", Currency.KZT),
        Country.LA to CountryMetadata("LA", "Laos", Currency.LAK),
        Country.LB to CountryMetadata("LB", "Lebanon", Currency.LBP),
        Country.LC to CountryMetadata("LC", "Saint Lucia", Currency.XCD),
        Country.LI to CountryMetadata("LI", "Liechtenstein", Currency.CHF),
        Country.LK to CountryMetadata("LK", "Sri Lanka", Currency.LKR),
        Country.LR to CountryMetadata("LR", "Liberia", Currency.LRD),
        Country.LS to CountryMetadata("LS", "Lesotho", Currency.LSL),
        Country.LT to CountryMetadata("LT", "Lithuania", Currency.EUR),
        Country.LU to CountryMetadata("LU", "Luxembourg", Currency.EUR),
        Country.LV to CountryMetadata("LV", "Latvia", Currency.EUR),
        Country.LY to CountryMetadata("LY", "Libya", Currency.LYD),
        Country.MA to CountryMetadata("MA", "Morocco", Currency.MAD),
        Country.MC to CountryMetadata("MC", "Monaco", Currency.EUR),
        Country.MD to CountryMetadata("MD", "Moldova", Currency.MDL),
        Country.ME to CountryMetadata("ME", "Montenegro", Currency.EUR),
        Country.MG to CountryMetadata("MG", "Madagascar", Currency.MGA),
        Country.MK to CountryMetadata("MK", "North Macedonia", Currency.MKD),
        Country.ML to CountryMetadata("ML", "Mali", Currency.XOF),
        Country.MM to CountryMetadata("MM", "Myanmar", Currency.MMK),
        Country.MN to CountryMetadata("MN", "Mongolia", Currency.MNT),
        Country.MO to CountryMetadata("MO", "Macau", Currency.MOP),
        Country.MR to CountryMetadata("MR", "Mauritania", Currency.MRU),
        Country.MT to CountryMetadata("MT", "Malta", Currency.EUR),
        Country.MU to CountryMetadata("MU", "Mauritius", Currency.MUR),
        Country.MV to CountryMetadata("MV", "Maldives", Currency.MVR),
        Country.MW to CountryMetadata("MW", "Malawi", Currency.MWK),
        Country.MX to CountryMetadata("MX", "Mexico", Currency.MXN),
        Country.MY to CountryMetadata("MY", "Malaysia", Currency.MYR),
        Country.MZ to CountryMetadata("MZ", "Mozambique", Currency.MZN),
        Country.NA to CountryMetadata("NA", "Namibia", Currency.NAD),
        Country.NE to CountryMetadata("NE", "Niger", Currency.XOF),
        Country.NG to CountryMetadata("NG", "Nigeria", Currency.NGN),
        Country.NI to CountryMetadata("NI", "Nicaragua", Currency.NIO),
        Country.NL to CountryMetadata("NL", "Netherlands", Currency.EUR),
        Country.NO to CountryMetadata("NO", "Norway", Currency.NOK),
        Country.NP to CountryMetadata("NP", "Nepal", Currency.NPR),
        Country.NR to CountryMetadata("NR", "Nauru", Currency.AUD),
        Country.NZ to CountryMetadata("NZ", "New Zealand", Currency.NZD),
        Country.OM to CountryMetadata("OM", "Oman", Currency.OMR),
        Country.PA to CountryMetadata("PA", "Panama", Currency.PAB),
        Country.PE to CountryMetadata("PE", "Peru", Currency.PEN),
        Country.PG to CountryMetadata("PG", "Papua New Guinea", Currency.PGK),
        Country.PH to CountryMetadata("PH", "Philippines", Currency.PHP),
        Country.PK to CountryMetadata("PK", "Pakistan", Currency.PKR),
        Country.PL to CountryMetadata("PL", "Poland", Currency.PLN),
        Country.PT to CountryMetadata("PT", "Portugal", Currency.EUR),
        Country.PW to CountryMetadata("PW", "Palau", Currency.USD),
        Country.PY to CountryMetadata("PY", "Paraguay", Currency.PYG),
        Country.QA to CountryMetadata("QA", "Qatar", Currency.QAR),
        Country.RO to CountryMetadata("RO", "Romania", Currency.RON),
        Country.RS to CountryMetadata("RS", "Serbia", Currency.RSD),
        Country.RU to CountryMetadata("RU", "Russia", Currency.RUB),
        Country.RW to CountryMetadata("RW", "Rwanda", Currency.RWF),
        Country.SA to CountryMetadata("SA", "Saudi Arabia", Currency.SAR),
        Country.SB to CountryMetadata("SB", "Solomon Islands", Currency.SBD),
        Country.SC to CountryMetadata("SC", "Seychelles", Currency.SCR),
        Country.SD to CountryMetadata("SD", "Sudan", Currency.SDG),
        Country.SE to CountryMetadata("SE", "Sweden", Currency.SEK),
        Country.SG to CountryMetadata("SG", "Singapore", Currency.SGD),
        Country.SI to CountryMetadata("SI", "Slovenia", Currency.EUR),
        Country.SK to CountryMetadata("SK", "Slovakia", Currency.EUR),
        Country.SL to CountryMetadata("SL", "Sierra Leone", Currency.SLL),
        Country.SM to CountryMetadata("SM", "San Marino", Currency.EUR),
        Country.SN to CountryMetadata("SN", "Senegal", Currency.XOF),
        Country.SO to CountryMetadata("SO", "Somalia", Currency.SOS),
        Country.SR to CountryMetadata("SR", "Suriname", Currency.SRD),
        Country.SS to CountryMetadata("SS", "South Sudan", Currency.SDG),
        Country.ST to CountryMetadata("ST", "São Tomé and Príncipe", Currency.STN),
        Country.SV to CountryMetadata("SV", "El Salvador", Currency.USD),
        Country.SY to CountryMetadata("SY", "Syria", Currency.SYP),
        Country.SZ to CountryMetadata("SZ", "Eswatini", Currency.SZL),
        Country.TD to CountryMetadata("TD", "Chad", Currency.XAF),
        Country.TG to CountryMetadata("TG", "Togo", Currency.XOF),
        Country.TH to CountryMetadata("TH", "Thailand", Currency.THB),
        Country.TJ to CountryMetadata("TJ", "Tajikistan", Currency.TJS),
        Country.TL to CountryMetadata("TL", "Timor-Leste", Currency.USD),
        Country.TM to CountryMetadata("TM", "Turkmenistan", Currency.TMT),
        Country.TN to CountryMetadata("TN", "Tunisia", Currency.TND),
        Country.TO to CountryMetadata("TO", "Tonga", Currency.TOP),
        Country.TR to CountryMetadata("TR", "Turkey", Currency.TRY),
        Country.TT to CountryMetadata("TT", "Trinidad and Tobago", Currency.TTD),
        Country.TV to CountryMetadata("TV", "Tuvalu", Currency.AUD),
        Country.TW to CountryMetadata("TW", "Taiwan", Currency.TWD),
        Country.TZ to CountryMetadata("TZ", "Tanzania", Currency.TZS),
        Country.UA to CountryMetadata("UA", "Ukraine", Currency.UAH),
        Country.UG to CountryMetadata("UG", "Uganda", Currency.UGX),
        Country.US to CountryMetadata("US", "United States", Currency.USD),
        Country.UY to CountryMetadata("UY", "Uruguay", Currency.UYU),
        Country.UZ to CountryMetadata("UZ", "Uzbekistan", Currency.UZS),
        Country.VA to CountryMetadata("VA", "Vatican City", Currency.EUR),
        Country.VC to CountryMetadata("VC", "Saint Vincent and the Grenadines", Currency.XCD),
        Country.VE to CountryMetadata("VE", "Venezuela", Currency.VES),
        Country.VN to CountryMetadata("VN", "Vietnam", Currency.VND),
        Country.VU to CountryMetadata("VU", "Vanuatu", Currency.VUV),
        Country.WS to CountryMetadata("WS", "Samoa", Currency.WST),
        Country.YE to CountryMetadata("YE", "Yemen", Currency.YER),
        Country.ZA to CountryMetadata("ZA", "South Africa", Currency.ZAR),
        Country.ZM to CountryMetadata("ZM", "Zambia", Currency.ZMW),
        Country.ZW to CountryMetadata("ZW", "Zimbabwe", Currency.ZWL)
    )

    fun get(country: Country): CountryMetadata =
        registry[country] ?: CountryMetadata(country.name, country.name, null)
}