package com.finance.shared

public data class CurrencyMetadata(
    val code: String,
    val fractionDigits: Int,
    val displayName: String
)

public val Currency.metadata: CurrencyMetadata get() = CurrencyMetadataRegistry.get(this)

internal object CurrencyMetadataRegistry {
    private val registry: Map<Currency, CurrencyMetadata> = buildMap {
        put(Currency.AED, CurrencyMetadata("AED", 2, "UAE Dirham"))
        put(Currency.AFN, CurrencyMetadata("AFN", 2, "Afghan Afghani"))
        put(Currency.ALL, CurrencyMetadata("ALL", 2, "Albanian Lek"))
        put(Currency.AMD, CurrencyMetadata("AMD", 2, "Armenian Dram"))
        put(Currency.ANG, CurrencyMetadata("ANG", 2, "Netherlands Antillean Guilder"))
        put(Currency.AOA, CurrencyMetadata("AOA", 2, "Angolan Kwanza"))
        put(Currency.ARS, CurrencyMetadata("ARS", 2, "Argentine Peso"))
        put(Currency.AUD, CurrencyMetadata("AUD", 2, "Australian Dollar"))
        put(Currency.AWG, CurrencyMetadata("AWG", 2, "Aruban Florin"))
        put(Currency.AZN, CurrencyMetadata("AZN", 2, "Azerbaijani Manat"))
        put(Currency.BAM, CurrencyMetadata("BAM", 2, "Bosnia-Herzegovina Convertible Mark"))
        put(Currency.BBD, CurrencyMetadata("BBD", 2, "Barbadian Dollar"))
        put(Currency.BDT, CurrencyMetadata("BDT", 2, "Bangladeshi Taka"))
        put(Currency.BGN, CurrencyMetadata("BGN", 2, "Bulgarian Lev"))
        put(Currency.BHD, CurrencyMetadata("BHD", 3, "Bahraini Dinar"))
        put(Currency.BIF, CurrencyMetadata("BIF", 0, "Burundian Franc"))
        put(Currency.BMD, CurrencyMetadata("BMD", 2, "Bermudan Dollar"))
        put(Currency.BND, CurrencyMetadata("BND", 2, "Brunei Dollar"))
        put(Currency.BOB, CurrencyMetadata("BOB", 2, "Bolivian Boliviano"))
        put(Currency.BRL, CurrencyMetadata("BRL", 2, "Brazilian Real"))
        put(Currency.BSD, CurrencyMetadata("BSD", 2, "Bahamian Dollar"))
        put(Currency.BTN, CurrencyMetadata("BTN", 2, "Bhutanese Ngultrum"))
        put(Currency.BWP, CurrencyMetadata("BWP", 2, "Botswanan Pula"))
        put(Currency.BYN, CurrencyMetadata("BYN", 2, "Belarusian Ruble"))
        put(Currency.BZD, CurrencyMetadata("BZD", 2, "Belize Dollar"))
        put(Currency.CAD, CurrencyMetadata("CAD", 2, "Canadian Dollar"))
        put(Currency.CDF, CurrencyMetadata("CDF", 2, "Congolese Franc"))
        put(Currency.CHF, CurrencyMetadata("CHF", 2, "Swiss Franc"))
        put(Currency.CLP, CurrencyMetadata("CLP", 0, "Chilean Peso"))
        put(Currency.CNY, CurrencyMetadata("CNY", 2, "Chinese Yuan"))
        put(Currency.COP, CurrencyMetadata("COP", 2, "Colombian Peso"))
        put(Currency.CRC, CurrencyMetadata("CRC", 2, "Costa Rican Colón"))
        put(Currency.CUP, CurrencyMetadata("CUP", 2, "Cuban Peso"))
        put(Currency.CVE, CurrencyMetadata("CVE", 2, "Cape Verdean Escudo"))
        put(Currency.CZK, CurrencyMetadata("CZK", 2, "Czech Koruna"))
        put(Currency.DJF, CurrencyMetadata("DJF", 0, "Djiboutian Franc"))
        put(Currency.DKK, CurrencyMetadata("DKK", 2, "Danish Krone"))
        put(Currency.DOP, CurrencyMetadata("DOP", 2, "Dominican Peso"))
        put(Currency.DZD, CurrencyMetadata("DZD", 2, "Algerian Dinar"))
        put(Currency.EGP, CurrencyMetadata("EGP", 2, "Egyptian Pound"))
        put(Currency.ERN, CurrencyMetadata("ERN", 2, "Eritrean Nakfa"))
        put(Currency.ETB, CurrencyMetadata("ETB", 2, "Ethiopian Birr"))
        put(Currency.EUR, CurrencyMetadata("EUR", 2, "Euro"))
        put(Currency.FJD, CurrencyMetadata("FJD", 2, "Fijian Dollar"))
        put(Currency.FKP, CurrencyMetadata("FKP", 2, "Falkland Islands Pound"))
        put(Currency.GBP, CurrencyMetadata("GBP", 2, "British Pound"))
        put(Currency.GEL, CurrencyMetadata("GEL", 2, "Georgian Lari"))
        put(Currency.GHS, CurrencyMetadata("GHS", 2, "Ghanaian Cedi"))
        put(Currency.GIP, CurrencyMetadata("GIP", 2, "Gibraltar Pound"))
        put(Currency.GMD, CurrencyMetadata("GMD", 2, "Gambian Dalasi"))
        put(Currency.GNF, CurrencyMetadata("GNF", 0, "Guinean Franc"))
        put(Currency.GTQ, CurrencyMetadata("GTQ", 2, "Guatemalan Quetzal"))
        put(Currency.GYD, CurrencyMetadata("GYD", 2, "Guyanaese Dollar"))
        put(Currency.HKD, CurrencyMetadata("HKD", 2, "Hong Kong Dollar"))
        put(Currency.HNL, CurrencyMetadata("HNL", 2, "Honduran Lempira"))
        put(Currency.HRK, CurrencyMetadata("HRK", 2, "Croatian Kuna"))
        put(Currency.HTG, CurrencyMetadata("HTG", 2, "Haitian Gourde"))
        put(Currency.HUF, CurrencyMetadata("HUF", 2, "Hungarian Forint"))
        put(Currency.IDR, CurrencyMetadata("IDR", 2, "Indonesian Rupiah"))
        put(Currency.ILS, CurrencyMetadata("ILS", 2, "Israeli Shekel"))
        put(Currency.INR, CurrencyMetadata("INR", 2, "Indian Rupee"))
        put(Currency.IQD, CurrencyMetadata("IQD", 3, "Iraqi Dinar"))
        put(Currency.IRR, CurrencyMetadata("IRR", 2, "Iranian Rial"))
        put(Currency.ISK, CurrencyMetadata("ISK", 0, "Icelandic Króna"))
        put(Currency.JMD, CurrencyMetadata("JMD", 2, "Jamaican Dollar"))
        put(Currency.JOD, CurrencyMetadata("JOD", 3, "Jordanian Dinar"))
        put(Currency.JPY, CurrencyMetadata("JPY", 0, "Japanese Yen"))
        put(Currency.KES, CurrencyMetadata("KES", 2, "Kenyan Shilling"))
        put(Currency.KGS, CurrencyMetadata("KGS", 2, "Kyrgystani Som"))
        put(Currency.KHR, CurrencyMetadata("KHR", 2, "Cambodian Riel"))
        put(Currency.KMF, CurrencyMetadata("KMF", 0, "Comorian Franc"))
        put(Currency.KPW, CurrencyMetadata("KPW", 2, "North Korean Won"))
        put(Currency.KRW, CurrencyMetadata("KRW", 0, "South Korean Won"))
        put(Currency.KWD, CurrencyMetadata("KWD", 3, "Kuwaiti Dinar"))
        put(Currency.KYD, CurrencyMetadata("KYD", 2, "Cayman Islands Dollar"))
        put(Currency.KZT, CurrencyMetadata("KZT", 2, "Kazakhstani Tenge"))
        put(Currency.LAK, CurrencyMetadata("LAK", 2, "Laotian Kip"))
        put(Currency.LBP, CurrencyMetadata("LBP", 2, "Lebanese Pound"))
        put(Currency.LKR, CurrencyMetadata("LKR", 2, "Sri Lankan Rupee"))
        put(Currency.LRD, CurrencyMetadata("LRD", 2, "Liberian Dollar"))
        put(Currency.LSL, CurrencyMetadata("LSL", 2, "Lesotho Loti"))
        put(Currency.LYD, CurrencyMetadata("LYD", 3, "Libyan Dinar"))
        put(Currency.MAD, CurrencyMetadata("MAD", 2, "Moroccan Dirham"))
        put(Currency.MDL, CurrencyMetadata("MDL", 2, "Moldovan Leu"))
        put(Currency.MGA, CurrencyMetadata("MGA", 2, "Malagasy Ariary"))
        put(Currency.MKD, CurrencyMetadata("MKD", 2, "Macedonian Denar"))
        put(Currency.MMK, CurrencyMetadata("MMK", 2, "Myanma Kyat"))
        put(Currency.MNT, CurrencyMetadata("MNT", 2, "Mongolian Tugrik"))
        put(Currency.MOP, CurrencyMetadata("MOP", 2, "Macanese Pataca"))
        put(Currency.MRU, CurrencyMetadata("MRU", 2, "Mauritanian Ouguiya"))
        put(Currency.MUR, CurrencyMetadata("MUR", 2, "Mauritian Rupee"))
        put(Currency.MVR, CurrencyMetadata("MVR", 2, "Maldivian Rufiyaa"))
        put(Currency.MWK, CurrencyMetadata("MWK", 2, "Malawian Kwacha"))
        put(Currency.MXN, CurrencyMetadata("MXN", 2, "Mexican Peso"))
        put(Currency.MYR, CurrencyMetadata("MYR", 2, "Malaysian Ringgit"))
        put(Currency.MZN, CurrencyMetadata("MZN", 2, "Mozambican Metical"))
        put(Currency.NAD, CurrencyMetadata("NAD", 2, "Namibian Dollar"))
        put(Currency.NGN, CurrencyMetadata("NGN", 2, "Nigerian Naira"))
        put(Currency.NIO, CurrencyMetadata("NIO", 2, "Nicaraguan Córdoba"))
        put(Currency.NOK, CurrencyMetadata("NOK", 2, "Norwegian Krone"))
        put(Currency.NPR, CurrencyMetadata("NPR", 2, "Nepalese Rupee"))
        put(Currency.NZD, CurrencyMetadata("NZD", 2, "New Zealand Dollar"))
        put(Currency.OMR, CurrencyMetadata("OMR", 3, "Omani Rial"))
        put(Currency.PAB, CurrencyMetadata("PAB", 2, "Panamanian Balboa"))
        put(Currency.PEN, CurrencyMetadata("PEN", 2, "Peruvian Sol"))
        put(Currency.PGK, CurrencyMetadata("PGK", 2, "Papua New Guinean Kina"))
        put(Currency.PHP, CurrencyMetadata("PHP", 2, "Philippine Peso"))
        put(Currency.PKR, CurrencyMetadata("PKR", 2, "Pakistani Rupee"))
        put(Currency.PLN, CurrencyMetadata("PLN", 2, "Polish Zloty"))
        put(Currency.PYG, CurrencyMetadata("PYG", 0, "Paraguayan Guarani"))
        put(Currency.QAR, CurrencyMetadata("QAR", 2, "Qatari Rial"))
        put(Currency.RON, CurrencyMetadata("RON", 2, "Romanian Leu"))
        put(Currency.RSD, CurrencyMetadata("RSD", 2, "Serbian Dinar"))
        put(Currency.RUB, CurrencyMetadata("RUB", 2, "Russian Ruble"))
        put(Currency.RWF, CurrencyMetadata("RWF", 0, "Rwandan Franc"))
        put(Currency.SAR, CurrencyMetadata("SAR", 2, "Saudi Riyal"))
        put(Currency.SBD, CurrencyMetadata("SBD", 2, "Solomon Islands Dollar"))
        put(Currency.SCR, CurrencyMetadata("SCR", 2, "Seychellois Rupee"))
        put(Currency.SDG, CurrencyMetadata("SDG", 2, "Sudanese Pound"))
        put(Currency.SEK, CurrencyMetadata("SEK", 2, "Swedish Krona"))
        put(Currency.SGD, CurrencyMetadata("SGD", 2, "Singapore Dollar"))
        put(Currency.SHP, CurrencyMetadata("SHP", 2, "Saint Helena Pound"))
        put(Currency.SLL, CurrencyMetadata("SLL", 2, "Sierra Leonean Leone"))
        put(Currency.SOS, CurrencyMetadata("SOS", 2, "Somali Shilling"))
        put(Currency.SRD, CurrencyMetadata("SRD", 2, "Surinamese Dollar"))
        put(Currency.STN, CurrencyMetadata("STN", 2, "São Tomé and Príncipe Dobra"))
        put(Currency.SVC, CurrencyMetadata("SVC", 2, "Salvadoran Colón"))
        put(Currency.SYP, CurrencyMetadata("SYP", 2, "Syrian Pound"))
        put(Currency.SZL, CurrencyMetadata("SZL", 2, "Swazi Lilangeni"))
        put(Currency.THB, CurrencyMetadata("THB", 2, "Thai Baht"))
        put(Currency.TJS, CurrencyMetadata("TJS", 2, "Tajikistani Somoni"))
        put(Currency.TMT, CurrencyMetadata("TMT", 2, "Turkmenistani Manat"))
        put(Currency.TND, CurrencyMetadata("TND", 3, "Tunisian Dinar"))
        put(Currency.TOP, CurrencyMetadata("TOP", 2, "Tongan Paʻanga"))
        put(Currency.TRY, CurrencyMetadata("TRY", 2, "Turkish Lira"))
        put(Currency.TTD, CurrencyMetadata("TTD", 2, "Trinidad and Tobago Dollar"))
        put(Currency.TWD, CurrencyMetadata("TWD", 2, "New Taiwan Dollar"))
        put(Currency.TZS, CurrencyMetadata("TZS", 2, "Tanzanian Shilling"))
        put(Currency.UAH, CurrencyMetadata("UAH", 2, "Ukrainian Hryvnia"))
        put(Currency.UGX, CurrencyMetadata("UGX", 0, "Ugandan Shilling"))
        put(Currency.USD, CurrencyMetadata("USD", 2, "US Dollar"))
        put(Currency.UYU, CurrencyMetadata("UYU", 2, "Uruguayan Peso"))
        put(Currency.UZS, CurrencyMetadata("UZS", 2, "Uzbekistan Som"))
        put(Currency.VES, CurrencyMetadata("VES", 2, "Venezuelan Bolívar"))
        put(Currency.VND, CurrencyMetadata("VND", 0, "Vietnamese Dong"))
        put(Currency.VUV, CurrencyMetadata("VUV", 0, "Vanuatu Vatu"))
        put(Currency.WST, CurrencyMetadata("WST", 2, "Samoan Tala"))
        put(Currency.XAF, CurrencyMetadata("XAF", 0, "CFA Franc BEAC"))
        put(Currency.XCD, CurrencyMetadata("XCD", 2, "East Caribbean Dollar"))
        put(Currency.XOF, CurrencyMetadata("XOF", 0, "CFA Franc BCEAO"))
        put(Currency.XPF, CurrencyMetadata("XPF", 0, "CFP Franc"))
        put(Currency.YER, CurrencyMetadata("YER", 2, "Yemeni Rial"))
        put(Currency.ZAR, CurrencyMetadata("ZAR", 2, "South African Rand"))
        put(Currency.ZMW, CurrencyMetadata("ZMW", 2, "Zambian Kwacha"))
        put(Currency.ZWL, CurrencyMetadata("ZWL", 2, "Zimbabwean Dollar"))
    }

    fun get(currency: Currency): CurrencyMetadata =
        registry[currency] ?: CurrencyMetadata(currency.name, 2, currency.name)
}